import { Inter } from 'next/font/google';
import './globals.css';
import styles from './page.module.css';
import NavBar from '@/components/nav/nav-bar';
const inter = Inter({ subsets: ['latin'] });

export const metadata = {
  title: 'Cruddy',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        {children}
      </body>
    </html>
  );
}
